networks:
  traefik_proxy:
    external: true

services:
  iota_tx_demo_ui:
    image: iota_tx_demo_ui:latest
    container_name: iota_tx_demo_ui
    build:
      context: .
      dockerfile: Dockerfile.iota-demo-ui
    restart: unless-stopped
    environment:
      IOTA_TEST_TX_SERVER_BIND: 0.0.0.0:8787
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.iota-tx-demo.rule=Host(`${IOTA_TX_DEMO_HOST:-iota-tx-demo.objectid.io}`)"
      - "traefik.http.routers.iota-tx-demo.entrypoints=websecure"
      - "traefik.http.routers.iota-tx-demo.tls=true"
      - "traefik.http.routers.iota-tx-demo.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-myresolver}"
      - "traefik.http.routers.iota-tx-demo.middlewares=iota-tx-demo-sec@docker,iota-tx-demo-cors@docker"

      - "traefik.http.services.iota-tx-demo.loadbalancer.server.port=8787"

      - "traefik.http.middlewares.iota-tx-demo-cors.headers.accessControlAllowMethods=GET,OPTIONS"
      - "traefik.http.middlewares.iota-tx-demo-cors.headers.accessControlAllowHeaders=*"
      - "traefik.http.middlewares.iota-tx-demo-cors.headers.accessControlAllowOriginList=http://unicore.objectid.io,https://unicore.objectid.io"
      - "traefik.http.middlewares.iota-tx-demo-cors.headers.accessControlMaxAge=100"
      - "traefik.http.middlewares.iota-tx-demo-cors.headers.addVaryHeader=true"

      - "traefik.http.middlewares.iota-tx-demo-sec.headers.permissionsPolicy=geolocation=(), camera=*, microphone=(), payment=(), usb=()"
      - "traefik.http.middlewares.iota-tx-demo-sec.headers.customResponseHeaders.Content-Security-Policy=default-src 'self' https://cdn.jsdelivr.net data: blob:; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; img-src 'self' data: blob:; connect-src 'self' http://unicore.objectid.io https://unicore.objectid.io https://api.testnet.iota.cafe https://gas1.objectid.io https://gas2.objectid.io;"
      - "traefik.http.middlewares.iota-tx-demo-sec.headers.stsSeconds=63072000"
      - "traefik.http.middlewares.iota-tx-demo-sec.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.iota-tx-demo-sec.headers.referrerPolicy=strict-origin-when-cross-origin"
      - "traefik.http.middlewares.iota-tx-demo-sec.headers.customResponseHeaders.X-Debug-Config=IOTA_TX_DEMO_UI"
