// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IotaNetwork } from "../iota_wallet/IotaNetwork";

export interface CreateOrLoadIotaWallet { network: IotaNetwork, }
