// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IotaNetwork } from "../iota_wallet/IotaNetwork";

export interface SignPreparedIotaTransaction { tx_data_bcs_base64: string | null, tx_kind_bcs_base64: string | null, gas_budget: number, gas_price: number | null, network: IotaNetwork, submit: boolean, }
