// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IotaNetwork } from "./IotaNetwork";

export interface IotaWalletState { network: IotaNetwork, address: string | null, public_key: string | null, seed_phrase: string | null, did: string | null, did_document: string | null, identity_controller_cap: string | null, identity_validation_status: string | null, identity_validation_error: string | null, identity_rotation_status: string | null, identity_destruction_status: string | null, faucet_status: string | null, last_transaction_digest: string | null, last_error: string | null, }
