// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface IotaWalletState { address: string | null, did: string | null, identity_controller_cap: string | null, last_transaction_digest: string | null, last_error: string | null, }
